### ISSUE TITLE
Needs Refreshed Token on Every Start

### ISSUE THREAD

**Issue by matthewabeke** [TrevTV/mb_CopySpotify#2]
Don't know if this is working as intended or not but on every start of MusicBee, it pops up saying it needs a refreshed Spotify token for it to work.

**Comment by TrevTV** [comment]
That is technically intended, but is definitely not preferable. Spotify's API access tokens must have lasted a lot shorter than I had expected. Once I have the time, I will add an option to use developer API keys instead of using a user token which should fix that issue.

**Comment by TrevTV** [comment]
Developer key support has now been added in release 1.0.2, if you have any issues with that release, please open a new issue.
