### ISSUE TITLE
Causes Musicbee to close down on startup entirely if unable to connect to spotify

### ISSUE THREAD

**Issue by Lyyfe** [TrevTV/mb_CopySpotify#6]
If you have the plugin enabled, and no internet access, then launching musicbee causes this error message to show up.
![image](https://github.com/TrevTV/mb_CopySpotify/assets/43151352/0765d3b5-3c5f-4247-8023-015d86ac0da9)
When you press OK afterwards then the entire program closes down. Of course I would be okay with the plugin simply not working and not telling me while I have no internet access, but having it close down musicbee is irritating.

Thanks in advanced :)

**Comment by TrevTV** [comment]
Would have been smart to add that check, not sure why I didn't. Will get to it ASAP

**Comment by TrevTV** [comment]
Easy fix! Release 1.1.1 is ready
https://github.com/TrevTV/mb_CopySpotify/releases/tag/1.1.1
